### ISSUE TITLE
NIC Internship Tasks

### ISSUE THREAD

**Issue by hashhar** [hashhar/notes-and-hacks#9]
# TODO:

- [x] DAO classes for every Hibernate Entity
- [x] Implement `Preparable` interface in `LicenceAction` class to populate the `listKeys` from the Database (`config_key_master`). **NOTE: Preparable doesn't work that way, instead use `response.redirect` or `jsp:forward`.
- [x] Check to see if dao needs to be modified for the new session based interface.
- [x] Fix `createlicence.jsp` to match the changes and add JavaScript validation. (see https://github.com/jzaefferer/jquery-validation and https://github.com/MorrisJobke/strengthify)
- [x] Check and see if we can get file upload working so that the LicenceFile can be gotten from the user. (`KeystoreLocation`)
- [x] Check and see if we can write a file to the user's machine or we have to allow the option of downloading it. (`OutFileLocation`)

- [x] Core Java

### Data Types

- [x] Strings
- [x] Collections
  - [x] Array List
  - [x] Map
  - [x] Hash Map
  - [x] Set
  - [x] Hash Set

### Java Web Applications

- [x] Servlet lifecycle
- [x] Struts
- [x] Struts 2 MVC
- [x] Apache Tomcat
- [x] JDBC 4 (ORM Tools)
- [x] jQuery Validation
